# Generated by Django 3.1 on 2021-07-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('treeCode', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('treeName', models.CharField(max_length=120)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('children', models.ManyToManyField(blank=True, related_name='_person_children_+', to='service.Person')),
                ('parents', models.ManyToManyField(blank=True, related_name='_person_parents_+', to='service.Person')),
                ('siblings', models.ManyToManyField(blank=True, related_name='_person_siblings_+', to='service.Person')),
                ('spouses', models.ManyToManyField(blank=True, related_name='_person_spouses_+', to='service.Person')),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='service.tree')),
            ],
        ),
    ]
