# Generated by Django 3.1 on 2021-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='treeCode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
