# Generated by Django 3.1 on 2021-07-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210704_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='treeCode',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False),
        ),
    ]
